; Tauri's installer strings for this language (tauri-bundler, MIT or
; Apache-2.0), with Kynoko Launcher's wording on the pages where an
; installed version meets a new one, and on the uninstaller's checkbox:
; users must see that their preferences are kept. Generated by
; tools/nsis-strings.py from the files a Tauri build writes; a string Tauri
; adds later is missing here until that script runs again.
LangString addOrReinstall ${LANG_TRADCHINESE} "重新安裝（保留您的偏好設定）。"
LangString alreadyInstalled ${LANG_TRADCHINESE} "已安裝"
LangString alreadyInstalledLong ${LANG_TRADCHINESE} "${PRODUCTNAME} ${VERSION} 已安裝。您的偏好設定（瀏覽器、應用程式、檔案類型）會保留。請選擇要執行的操作，然後點擊「下一步」繼續。"
LangString appRunning ${LANG_TRADCHINESE} "{{product_name}} 正在執行中！請先關閉再進行嘗試。"
LangString appRunningOkKill ${LANG_TRADCHINESE} "{{product_name}} 正在執行中！點選確定後終止。"
LangString chooseMaintenanceOption ${LANG_TRADCHINESE} "請選擇你要進行的維護選項。"
LangString choowHowToInstall ${LANG_TRADCHINESE} "選擇你要如何安裝 ${PRODUCTNAME}。"
LangString createDesktop ${LANG_TRADCHINESE} "建立桌面捷徑"
LangString dontUninstall ${LANG_TRADCHINESE} "直接安裝在舊版本之上"
LangString dontUninstallDowngrade ${LANG_TRADCHINESE} "請勿解除安裝（本安裝程式不允許未解除安裝就進行版本降低的操作）"
LangString failedToKillApp ${LANG_TRADCHINESE} "無法終止 {{product_name}}。請先關閉再進行嘗試。"
LangString installingWebview2 ${LANG_TRADCHINESE} "WebView2 安裝中..."
LangString newerVersionInstalled ${LANG_TRADCHINESE} "已安裝更新版本的 ${PRODUCTNAME}！不建議安裝舊版。如果真的想要安裝舊版的話，最好先解除安裝現在的版本。選擇你想要進行的操作後再進行下一步。"
LangString older ${LANG_TRADCHINESE} "舊版"
LangString olderOrUnknownVersionInstalled ${LANG_TRADCHINESE} "系統中已安裝 ${PRODUCTNAME} $R4 版本。無論您如何選擇，您的偏好設定（瀏覽器、應用程式、檔案類型）都會保留。請選擇要執行的操作，然後點擊「下一步」繼續。"
LangString silentDowngrades ${LANG_TRADCHINESE} "本安裝程式不允許未解除安裝就進行版本降低的操作，無法繼續無聲安裝，請改用圖形化介面安裝。$\n"
LangString unableToUninstall ${LANG_TRADCHINESE} "無法解除安裝！"
LangString uninstallApp ${LANG_TRADCHINESE} "解除安裝 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_TRADCHINESE} "取代舊版本（建議）"
LangString unknown ${LANG_TRADCHINESE} "未知"
LangString webview2AbortError ${LANG_TRADCHINESE} "無法安裝 WebView2！這個應用程式需要安裝 WebView2 才能執行。請重新啟動安裝程式。"
LangString webview2DownloadError ${LANG_TRADCHINESE} "錯誤：WebView2 下載失敗 - $0"
LangString webview2DownloadSuccess ${LANG_TRADCHINESE} "WebView2 啟動載入器下載成功"
LangString webview2Downloading ${LANG_TRADCHINESE} "正在下載 WebView2 啟動載入器..."
LangString webview2InstallError ${LANG_TRADCHINESE} "錯誤：WebView2 安裝失敗，錯誤碼 $1"
LangString webview2InstallSuccess ${LANG_TRADCHINESE} "WebView2 安裝成功"
LangString deleteAppData ${LANG_TRADCHINESE} "同時刪除我的偏好設定（瀏覽器、應用程式、檔案類型）"
