#!/usr/bin/env python3
"""The Windows installer: Tauri's own NSIS template and language files, at
the version of the Tauri CLI in use, with Kynoko Launcher's changes.

Usage: python tools/nsis-installer.py   (after `npm ci` in app/; network)

Writes app/src-tauri/windows/installer.nsi and windows/lang/<Language>.nsh,
which tauri.conf.json points to (bundle.windows.nsis.template and
customLanguageFiles). Run it again after upgrading @tauri-apps/cli: every
change below is checked to still apply, and the script stops if one does not.

WHY. Installed over an existing version, Tauri's page offers two ways of
INSTALLING ("uninstall before installing" / "do not uninstall"), which read
as a riddle, and its same-version "Uninstall" uninstalls then reinstalls.
Here the page offers what a user expects: update (or reinstall), or
uninstall, the latter a real uninstall that ends the installer. Installing an
OLDER version keeps Tauri's page.
"""
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
APP = os.path.join(ROOT, 'app')
TAURI = os.path.join(APP, 'src-tauri')
OUT_TEMPLATE = os.path.join(TAURI, 'windows', 'installer.nsi')
OUT_LANG = os.path.join(TAURI, 'windows', 'lang')
CONF = os.path.join(TAURI, 'tauri.conf.json')

VERSION = json.load(open(os.path.join(APP, 'node_modules', '@tauri-apps', 'cli', 'package.json'), encoding='utf-8'))['version']
BASE = f'https://raw.githubusercontent.com/tauri-apps/tauri/tauri-cli-v{VERSION}/crates/tauri-bundler/src/bundle/windows/nsis'
LANGUAGES = ['French', 'English', 'Spanish', 'Japanese', 'SimpChinese', 'TradChinese', 'Arabic']


def fetch(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode('utf-8').lstrip('﻿')


def replace_once(text, old, new, what):
    if text.count(old) != 1:
        sys.exit(f'nsis-installer: "{what}" no longer applies to Tauri {VERSION}\'s template; update tools/nsis-installer.py.')
    return text.replace(old, new, 1)


# ---------------------------------------------------------------- template
template = fetch(f'{BASE}/installer.nsi')

template = replace_once(template, '''  ${ElseIf} $R0 = 1
    StrCpy $R1 "$(olderOrUnknownVersionInstalled)"
    StrCpy $R2 "$(uninstallBeforeInstalling)"
    StrCpy $R3 "$(dontUninstall)"''', '''  ${ElseIf} $R0 = 1
    ; Kynoko Launcher: update, or uninstall (tools/nsis-installer.py).
    StrCpy $R1 "$(olderOrUnknownVersionInstalled)"
    StrCpy $R2 "$(updateApp)"
    StrCpy $R3 "$(uninstallApp)"''', 'upgrade page choices')

template = replace_once(template, '''  ${If} $R0 = 0 ; Same version, proceed
    ${If} $R1 = 1              ; User chose to add/reinstall
      Goto reinst_done
    ${Else}                    ; User chose to uninstall
      Goto reinst_uninstall
    ${EndIf}
  ${ElseIf} $R0 = 1 ; Upgrading
    ${If} $R1 = 1              ; User chose to uninstall
      Goto reinst_uninstall
    ${Else}
      Goto reinst_done         ; User chose NOT to uninstall
    ${EndIf}''', '''  ; Kynoko Launcher (tools/nsis-installer.py): same version or upgrade,
  ; the first choice installs over the existing one (the user's preferences
  ; are kept), the second is a REAL uninstall that ends this installer.
  ${If} $R0 = 0 ; Same version
  ${OrIf} $R0 = 1 ; Upgrading
    ${If} $R1 = 1
      Goto reinst_done
    ${Else}
      Goto kynoko_uninstall
    ${EndIf}''', 'same-version and upgrade choices')

template = replace_once(template, '''  reinst_uninstall:
    HideWindow''', '''  ; A real uninstall, as from Windows' settings: the uninstaller copies
  ; itself out of the install folder and runs from there, so the launcher's
  ; cleanup runs (windows/hooks.nsh), with its "also delete my preferences"
  ; box. Nothing is installed afterwards. (Falling through from above keeps
  ; going where Tauri's code went.)
  Goto reinst_uninstall
  kynoko_uninstall:
    ReadRegStr $R1 SHCTX "${UNINSTKEY}" "UninstallString"
    Exec '$R1'
    Quit

  reinst_uninstall:
    HideWindow''', 'uninstall label')

header = (f'; Tauri {VERSION}\'s NSIS installer template (tauri-bundler, MIT or Apache-2.0),\n'
          '; with Kynoko Launcher\'s changes to the "already installed" page. GENERATED by\n'
          '; tools/nsis-installer.py: edit that script, not this file.\n')
os.makedirs(os.path.dirname(OUT_TEMPLATE), exist_ok=True)
open(OUT_TEMPLATE, 'w', encoding='utf-8', newline='\n').write(header + template)

# ---------------------------------------------------------------- strings
# Only what the pages above show, and the uninstaller's box. No em dash.
OVERRIDES = {
    'French': {
        'alreadyInstalled': "Déjà installé.",
        'alreadyInstalledLong': "${PRODUCTNAME} ${VERSION} est déjà installé. Choisissez l'opération souhaitée, puis cliquez sur Suivant.",
        'olderOrUnknownVersionInstalled': "Une autre version de ${PRODUCTNAME} est installée. Choisissez l'opération souhaitée, puis cliquez sur Suivant.",
        'newerVersionInstalled': "Une version plus récente de ${PRODUCTNAME} est déjà installée. Installer une version plus ancienne n'est pas recommandé. Choisissez l'opération souhaitée, puis cliquez sur Suivant.",
        'choowHowToInstall': "Choisissez l'opération à effectuer.",
        'updateApp': "Mettre à jour (vos préférences sont conservées)",
        'addOrReinstall': "Réinstaller (vos préférences sont conservées)",
        'uninstallApp': "Désinstaller ${PRODUCTNAME}",
        'deleteAppData': "Supprimer aussi mes préférences (navigateur, apps, types de fichiers)",
    },
    'English': {
        'olderOrUnknownVersionInstalled': "Another version of ${PRODUCTNAME} is installed. Select the operation you want to perform and click Next to continue.",
        'updateApp': "Update (your preferences are kept)",
        'addOrReinstall': "Reinstall (your preferences are kept)",
        'deleteAppData': "Also delete my preferences (browser, apps, file types)",
    },
    'Spanish': {
        'olderOrUnknownVersionInstalled': "Hay otra versión de ${PRODUCTNAME} instalada. Seleccione la operación que desea realizar y haga clic en Siguiente para continuar.",
        'updateApp': "Actualizar (sus preferencias se conservan)",
        'addOrReinstall': "Reinstalar (sus preferencias se conservan)",
        'deleteAppData': "Eliminar también mis preferencias (navegador, apps, tipos de archivo)",
    },
    'Japanese': {
        'olderOrUnknownVersionInstalled': "${PRODUCTNAME} の別のバージョンがインストールされています。実行する操作を選択し、[次へ] をクリックしてください。",
        'updateApp': "更新する（設定は保持されます）",
        'addOrReinstall': "再インストールする（設定は保持されます）",
        'deleteAppData': "設定（ブラウザー、アプリ、ファイルの種類）も削除する",
    },
    'SimpChinese': {
        'olderOrUnknownVersionInstalled': "已安装 ${PRODUCTNAME} 的另一个版本。请选择要执行的操作，然后点击“下一步”继续。",
        'updateApp': "更新（保留您的偏好设置）",
        'addOrReinstall': "重新安装（保留您的偏好设置）",
        'deleteAppData': "同时删除我的偏好设置（浏览器、应用、文件类型）",
    },
    'TradChinese': {
        'olderOrUnknownVersionInstalled': "已安裝 ${PRODUCTNAME} 的另一個版本。請選擇要執行的操作，然後點擊「下一步」繼續。",
        'updateApp': "更新（保留您的偏好設定）",
        'addOrReinstall': "重新安裝（保留您的偏好設定）",
        'deleteAppData': "同時刪除我的偏好設定（瀏覽器、應用程式、檔案類型）",
    },
    'Arabic': {
        'olderOrUnknownVersionInstalled': "إصدار آخر من ${PRODUCTNAME} مثبّت. اختر العملية التي تريد تنفيذها، ثم انقر على التالي للمتابعة.",
        'updateApp': "تحديث (تبقى تفضيلاتك محفوظة)",
        'addOrReinstall': "إعادة التثبيت (تبقى تفضيلاتك محفوظة)",
        'deleteAppData': "حذف تفضيلاتي أيضًا (المتصفح، التطبيقات، أنواع الملفات)",
    },
}
# Strings of ours that Tauri's files do not have: added, in every language.
NEW_KEYS = {'updateApp'}

HEADER = (f"; Tauri {VERSION}'s installer strings for this language (tauri-bundler, MIT\n"
          "; or Apache-2.0), with Kynoko Launcher's wording on the pages where an\n"
          "; installed version meets a new one, and on the uninstaller's box.\n"
          "; GENERATED by tools/nsis-installer.py: edit that script, not this file.\n")

os.makedirs(OUT_LANG, exist_ok=True)
files = {}
for lang in LANGUAGES:
    over = OVERRIDES[lang]
    missing_new = NEW_KEYS - set(over)
    if missing_new:
        sys.exit(f'nsis-installer: {lang} lacks {missing_new}')
    lines, seen, lang_id = [], set(), None
    for line in fetch(f'{BASE}/languages/{lang}.nsh').splitlines():
        m = re.match(r'LangString (\w+) (\$\{LANG_\w+\}) "(.*)"$', line)
        if m:
            lang_id = m.group(2)
            if m.group(1) in over:
                line = f'LangString {m.group(1)} {lang_id} "{over[m.group(1)]}"'
                seen.add(m.group(1))
        lines.append(line)
    for key in sorted(NEW_KEYS):
        lines.append(f'LangString {key} {lang_id} "{over[key]}"')
        seen.add(key)
    unknown = set(over) - seen
    if unknown:
        sys.exit(f'nsis-installer: {lang}: Tauri {VERSION} has no {unknown}')
    # No BOM: Tauri adds one when it copies the file (two make makensis fail).
    open(os.path.join(OUT_LANG, f'{lang}.nsh'), 'w', encoding='utf-8', newline='\n').write(HEADER + '\n'.join(lines) + '\n')
    files[lang] = f'windows/lang/{lang}.nsh'

# ---------------------------------------------------------------- config
conf = open(CONF, encoding='utf-8').read()
if '"template"' not in conf:
    conf = replace_once(conf, '        "installMode": "currentUser",', '        "installMode": "currentUser",\n        "template": "windows/installer.nsi",', 'tauri.conf template')
    json.loads(conf)
    open(CONF, 'w', encoding='utf-8', newline='\n').write(conf)
print(f'Tauri {VERSION}: windows/installer.nsi and {len(files)} language files written.')
